spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    redis:
        host: localhost
        port: 6379
logging:
    level:
        org.springframework.orm.jpa: DEBUG
        org.hibernate.or.jdbc.bind: DEBUG
        org.springframework.jdbc.core.JdbcTemplate: DEBUG
        org.springframework.transaction: DEBUG
jwt:
    secret: ${SECRET_KEY}

cloud:
    aws:
        s3:
            bucket-name: inho
        credentials:
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
        region:
            static: ap-northeast-2
        stack:
            auto: false
